apiVersion: app.onet.bigtree.space/v1alpha1
kind: Impress
metadata:
  name: toto-impress
  namespace: toto
spec:
  image:
    repository: lasuite/impress-backend
    pullPolicy: Always
    tag: "latest"
  backend:
    replicas: 1
    envVars:
      SSL_VERIFY: false
      COLLABORATION_API_URL: https://impress-dev.onet.bigtree.space/collaboration/api/
      COLLABORATION_SERVER_SECRET: my-secret
      DJANGO_CSRF_TRUSTED_ORIGINS: https://impress-dev.onet.bigtree.space
      DJANGO_CONFIGURATION: Feature
      DJANGO_ALLOWED_HOSTS: impress-dev.onet.bigtree.space
      DJANGO_SERVER_TO_SERVER_API_TOKENS: secret-api-key
      DJANGO_SECRET_KEY: AgoodOrAbadKey
      DJANGO_SETTINGS_MODULE: impress.settings
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_EMAIL_BRAND_NAME: "La Suite Numérique"
      DJANGO_EMAIL_HOST: "mailcatcher"
      DJANGO_EMAIL_LOGO_IMG: https://impress-dev.onet.bigtree.space/assets/logo-suite-numerique.png
      DJANGO_EMAIL_PORT: 1025
      DJANGO_EMAIL_USE_SSL: False
      LOGGING_LEVEL_HANDLERS_CONSOLE: ERROR
      LOGGING_LEVEL_LOGGERS_ROOT: INFO
      LOGGING_LEVEL_LOGGERS_APP: INFO
      OIDC_OP_JWKS_ENDPOINT: https://keycloak.onet.bigtree.space/realms/impress/protocol/openid-connect/certs
      OIDC_OP_AUTHORIZATION_ENDPOINT: https://keycloak.onet.bigtree.space/realms/impress/protocol/openid-connect/auth
      OIDC_OP_TOKEN_ENDPOINT: https://keycloak.onet.bigtree.space/realms/impress/protocol/openid-connect/token
      OIDC_OP_USER_ENDPOINT: https://keycloak.onet.bigtree.space/realms/impress/protocol/openid-connect/userinfo
      OIDC_OP_LOGOUT_ENDPOINT: https://keycloak.onet.bigtree.space/realms/impress/protocol/openid-connect/session/end
      OIDC_RP_CLIENT_ID: impress
      OIDC_RP_CLIENT_SECRET: ThisIsAnExampleKeyForDevPurposeOnly
      OIDC_RP_SIGN_ALGO: RS256
      OIDC_RP_SCOPES: "openid email"
      OIDC_VERIFY_SSL: False
      OIDC_USERINFO_SHORTNAME_FIELD: "given_name"
      OIDC_USERINFO_FULLNAME_FIELDS: "given_name,usual_name"
      OIDC_REDIRECT_ALLOWED_HOSTS: https://impress-dev.onet.bigtree.space
      OIDC_AUTH_REQUEST_EXTRA_PARAMS: "{'acr_values': 'eidas1'}"
      LOGIN_REDIRECT_URL: https://impress-dev.onet.bigtree.space
      LOGIN_REDIRECT_URL_FAILURE: https://impress-dev.onet.bigtree.space
      LOGOUT_REDIRECT_URL: https://impress-dev.onet.bigtree.space
      POSTHOG_KEY: "{'id': 'posthog_key', 'host': 'https://product.impress-dev.onet.bigtree.space'}"
      DB_HOST: postgresql
      DB_NAME: impress
      DB_USER: dinum
      DB_PASSWORD: pass
      DB_PORT: 5432
      POSTGRES_DB: impress
      POSTGRES_USER: dinum
      POSTGRES_PASSWORD: pass
      REDIS_URL: redis://default:pass@redis-master:6379/1
      AWS_S3_ENDPOINT_URL: http://minio.impress.svc.cluster.local:9000
      AWS_S3_ACCESS_KEY_ID: root
      AWS_S3_SECRET_ACCESS_KEY: password
      AWS_STORAGE_BUCKET_NAME: impress-media-storage
      STORAGES_STATICFILES_BACKEND: django.contrib.staticfiles.storage.StaticFilesStorage
      Y_PROVIDER_API_BASE_URL: http://impress-y-provider:443/api/
      Y_PROVIDER_API_KEY: my-secret
    migrate:
      command:
        - "/bin/sh"
        - "-c"
        - |
          python manage.py migrate --no-input &&
          python manage.py create_demo --force
      restartPolicy: Never
    command:
      - "gunicorn"
      - "-c"
      - "/usr/local/etc/gunicorn/impress.py"
      - "impress.wsgi:application"
      - "--reload"
    createsuperuser:
      command:
        - "/bin/sh"
        - "-c"
        - |
          python manage.py createsuperuser --email admin@example.com --password admin
      restartPolicy: Never
  frontend:
    envVars:
      PORT: 8080
      NEXT_PUBLIC_API_ORIGIN: https://impress-dev.onet.bigtree.space
    replicas: 1
    image:
      repository: lasuite/impress-frontend
      pullPolicy: Always
      tag: "latest"
  yProvider:
    replicas: 1
    image:
      repository: lasuite/impress-y-provider
      pullPolicy: Always
      tag: "latest"
    envVars:
      COLLABORATION_LOGGING: true
      COLLABORATION_SERVER_ORIGIN: https://impress-dev.onet.bigtree.space
      COLLABORATION_SERVER_SECRET: my-secret
      Y_PROVIDER_API_KEY: my-secret
  posthog:
    ingress:
      enabled: false
    ingressAssets:
      enabled: false
  ingress:
    enabled: true
    host: impress-dev.onet.bigtree.space
    tls:
      enabled: true
      secretName: impress-tls
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
  ingressCollaborationWS:
    enabled: true
    host: impress-dev.onet.bigtree.space
    tls:
      enabled: true
      secretName: impress-collab-tls
    annotations:
      nginx.ingress.kubernetes.io/auth-url: https://impress-dev.onet.bigtree.space/api/v1.0/documents/collaboration-auth/
      cert-manager.io/cluster-issuer: "letsencrypt"
  ingressCollaborationApi:
    enabled: true
    host: impress-dev.onet.bigtree.space
    tls:
      enabled: true
      secretName: impress-collab-api-tls
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
  ingressAdmin:
    enabled: true
    host: impress-dev.onet.bigtree.space
    tls:
      enabled: true
      secretName: impress-admin-tls
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
  ingressMedia:
    enabled: true
    host: impress-dev.onet.bigtree.space
    tls:
      enabled: true
      secretName: impress-media-tls
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/auth-url: https://impress-dev.onet.bigtree.space/api/v1.0/documents/media-auth/
      nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Amz-Date, X-Amz-Content-SHA256"
      nginx.ingress.kubernetes.io/upstream-vhost: minio.impress.svc.cluster.local:9000
      nginx.ingress.kubernetes.io/rewrite-target: /impress-media-storage/$1
      cert-manager.io/cluster-issuer: "letsencrypt"
  serviceMedia:
    host: minio.impress.svc.cluster.local
    port: 9000